CREATE TABLE IF NOT EXISTS vocab (
  id INTEGER PRIMARY KEY,
  vec BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS puzzles (
  id INTEGER PRIMARY KEY,
  answer TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
  name TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
