CREATE TABLE IF NOT EXISTS words (
  word TEXT PRIMARY KEY,
  vec BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS puzzles (
  id INTEGER PRIMARY KEY,
  answer TEXT NOT NULL,
  concepts TEXT NOT NULL,
  ks TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
  name TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS anchors (
  id INTEGER PRIMARY KEY,
  vec BLOB NOT NULL,
  count INTEGER NOT NULL,
  dim INTEGER NOT NULL
);
